### ISSUE TITLE
CDI 3.0 TCK challenge of incorrect type assumptions in EnvInjectionTest#testResourceBeanTypes under Java SE 12+

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/cdi-tck#241]
Testing with Java SE 17 (early access) to run https://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.1-dist.zip tests  + WildFly master is seeing failure:

```Tests run: 1796, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,623.551 s <<< FAILURE! - in TestSuite
[ERROR] org.jboss.cdi.tck.tests.implementation.simple.resource.env.EnvInjectionTest.testResourceBeanTypes  Time elapsed: 0.04 s  <<< FAILURE!
java.lang.AssertionError
	at deployment.dedc6d5ace7963e7119a9865eca6c1a74203870.war//org.jboss.cdi.tck.tests.implementation.simple.resource.env.EnvInjectionTest.testResourceBeanTypes
```
This is already resolved for upstream issue https://github.com/eclipse-ee4j/cdi-tck/issues/238.  

Needed action:
- Please add `challenge` label for this issue.
- Within two weeks, please accept this challenge or reject it.
- If the challenge is accepted, please exclude the `org.jboss.cdi.tck.tests.implementation.simple.resource.env.EnvInjectionTest.testResourceBeanTypes` test to be in the cdi-tck-3.0.2-dist.zip or in the next cdi-tck-3.0.*-dist.zip release.

**Comment by starksm64** [comment]
To create an exception list we need to resin a release, so we might as well fix the issue in the 3.0 branch and release a 3.0.2 version.

**Comment by starksm64** [comment]
3.0.3 TCK has been promoted:
https://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.3-dist.zip

**Comment by scottmarlow** [comment]
Thanks Scott, will run this now!

**Comment by scottmarlow** [comment]
With Java SE 17 (EA) I am still seeing:
```
wget --no-cache https://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.3-dist.zip -O latest-cdi-tck-dist.zip
...
sha256sum latest-cdi-tck-dist.zip
e1074a7965c801f3c421113d7a329890a222b619c9bf813e7f1082d225321449
...

[ERROR] Tests run: 1796, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,552.318 s <<< FAILURE! - in TestSuite
[ERROR] org.jboss.cdi.tck.tests.implementation.simple.resource.env.EnvInjectionTest.testResourceBeanTypes  Time elapsed: 0.035 s  <<< FAILURE!
java.lang.AssertionError
	at deployment.dedc6d5ace7963e7119a9865eca6c1a74203870.war//org.jboss.cdi.tck.tests.implementation.simple.resource.env.EnvInjectionTest.testResourceBeanTypes(EnvInjectionTest.java:83)
```

**Comment by starksm64** [comment]
Ok, I'll take a look

**Comment by starksm64** [comment]
I'm able to run the embedded tests fine using Java 17, but I'm back to not being able to run against a build of wildfly main branch because of some arquillian issue. I'll have to track this down first. 

```bash
INFO: Invoke EnterpriseInterceptorBindingResolutionTest.testLifecycleInterceptorBindings: 21/1,796 Failed tests: 0 (17)
[Utils] [ERROR] [Error] java.lang.RuntimeException: java.lang.RuntimeException: org.jboss.arquillian.container.spi.client.container.LifecycleException: The java process starting the managed server exited unexpectedly with code [1]
	at org.jboss.arquillian.testng.Arquillian$1.initialValue(Arquillian.java:63)
	at org.jboss.arquillian.testng.Arquillian$1.initialValue(Arquillian.java:55)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at org.jboss.arquillian.testng.Arquillian.arquillianArgumentProvider(Arquillian.java:240)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.lang.RuntimeException: org.jboss.arquillian.container.spi.client.container.LifecycleException: The java process starting the managed server exited unexpectedly with code [1]
	at org.jboss.weld.tck.wildfly8.WildFly8EEResourceManager.checkResources(WildFly8EEResourceManager.java:59)
	at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:54)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$2.perform(ContainerLifecycleController.java:70)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$2.perform(ContainerLifecycleController.java:64)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forEachSuiteContainer(ContainerLifecycleController.java:181)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.startSuiteContainers(ContainerLifecycleController.java:64)
	at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:71)
	at org.jboss.arquillian.testng.Arquillian$1.initialValue(Arquillian.java:60)
	... 40 more
Caused by: org.jboss.arquillian.container.spi.client.container.LifecycleException: The java process starting the managed server exited unexpectedly with code [1]
	at org.jboss.as.arquillian.container.CommonManagedDeployableContainer.startInternal(CommonManagedDeployableContainer.java:87)
	at org.jboss.as.arquillian.container.CommonDeployableContainer.start(CommonDeployableContainer.java:131)
	at org.jboss.arquillian.container.impl.ContainerImpl.start(ContainerImpl.java:179)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:137)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:133)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forContainer(ContainerLifecycleController.java:208)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.startContainer(ContainerLifecycleController.java:133)
	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.weld.tck.wildfly8.WildFly8EEResourceManager.checkResources(WildFly8EEResourceManager.java:40)
	... 84 more
```

**Comment by scottmarlow** [comment]
I have a hack for the ^ failure, I'll paste it in here.

**Comment by starksm64** [comment]
There are changes needed to the src/test/wildfly8/arquillian.xml and pom.xml from the weld/jboss-tck-runner to not pass in obsolete GC arguments that Java SE 17 rejects and for the module opens statements. I'll see if I can update the build of the dist/weld porting package contents to include this without a new release of weld.

**Comment by scottmarlow** [comment]
> There are changes needed to the src/test/wildfly8/arquillian.xml and pom.xml from the weld/jboss-tck-runner to not pass in obsolete GC arguments that Java SE 17 rejects and for the module opens statements. I'll see if I can update the build of the dist/weld porting package contents to include this without a new release of weld.

^ above steps are using https://github.com/scottmarlow/core/tree/wildfly_jdk17 which removes the obsolete arguments.

**Comment by starksm64** [comment]
Ok, technically these are just configuration changes and doing that to pass the TCK is allowed and fine. I will work on getting the bundled weld porting package to run against the current weld release and wildfly-24.0.0.Beta1

**Comment by scottmarlow** [comment]
Steps to reproduce with WildFly that is already copied to wildfly local folder folder (from wildfly/ee-9/dist/target/wildfly-preview-25.0.0.Beta1-SNAPSHOT):
```
WORKSPACE=$PWD
wget --no-cache https://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.3-dist.zip -O latest-cdi-tck-dist.zip
unzip latest-cdi-tck-dist.zip
MAVEN_OPTS="-Xmx1800m -XX:-UseGCOverheadLimit"
export MAVEN_OPTS
export JBOSS_DIR=wildfly
export JBOSS_ZIP=./wildfly.zip
cd cdi-tck-3.0.3/artifacts
export TCK_VERSION=3.0.3
bash artifact-install.sh $TCK_VERSION
cd $WORKSPACE
git clone https://github.com/scottmarlow/core weld
cd weld
git checkout wildfly_jdk17
mvn clean install -DskipTests
export JBOSS_HOME=${WORKSPACE}/${JBOSS_DIR}
mvn $JDK17OPTIONS clean package -Dtck -Dcdi.tck.version=${TCK_VERSION} -f jboss-as/pom.xml
mvn $JDK17OPTIONS clean verify -f jboss-tck-runner/pom.xml -Dincontainer -Dcdi.tck.version=${TCK_VERSION} -Dmaven.test.failure.ignore=true 
```

**Comment by scottmarlow** [comment]
To debug wildfly running EnvInjectionTest#testResourceBeanTypes, I tried the following but my breakpoint didn't seem to be reached in the EnvInjectionTest code:
```
mvn -Dadditional.vm.args="-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=y" $JDK17OPTIONS clean verify -f jboss-tck-runner/pom.xml -Dincontainer -Dcdi.tck.version=${TCK_VERSION} -Dmaven.test.failure.ignore=true test -Dtest=org.jboss.cdi.tck.tests.implementation.simple.resource.env.EnvInjectionTest 
```

@starksm64 any suggestions for how to debug the failing test as deployed in the loaded WildFly?

**Comment by scottmarlow** [comment]
For reference from the started WildFly server.log:
```
VM Arguments: -D[Standalone] -Xms128m -Xmx1g -ea -ea -DcdiTckExcludeDummy=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=y -Djboss.home.dir=/tmp/wildfly --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-modules=java.se -Djboss.home.dir=/tmp/wildfly -Djboss.server.base.dir=/tmp/wildfly/standalone -Djboss.server.log.dir=/tmp/wildfly/standalone/log -Djboss.server.config.dir=/tmp/wildfly/standalone/configuration -Dorg.jboss.boot.log.file=/tmp/wildfly/standalone/log/server.log -Dlogging.configuration=file:/tmp/wildfly/standalone/configuration/logging.properties

```

**Comment by scottmarlow** [comment]
Also for reference, https://github.com/scottmarlow/core/commit/ba556b5abae01df7ac4c17e13710f1edc10dcb18 is where I specified the JDK 17 options for the TCK testing with WildFly.

**Comment by scottmarlow** [comment]
Hmm, just noticed rookie mistake, the line numbers in the source I am debugging with is different :-)

**Comment by scottmarlow** [comment]
Tip from James Perkins helped, using -Dsurefire.plugin.jdk9.args=-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=y
```
mvn -Dsurefire.plugin.jdk9.args=-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=y $JDK17OPTIONS clean verify -f jboss-tck-runner/pom.xml -Dincontainer -Dcdi.tck.version=${TCK_VERSION} -Dmaven.test.failure.ignore=true test -Dtest=org.jboss.cdi.tck.tests.implementation.simple.resource.env.EnvInjectionTest
```

**Comment by scottmarlow** [comment]
From debugging, it seems like I am not using the CDI TCK 3.0.3 TCK but instead am using 3.0.1 as I get jdb failures like:
```
Unable to set deferred breakpoint org.jboss.cdi.tck.tests.implementation.simple.resource.env.EnvInjectionTest:86 : No code at line 86 in org.jboss.cdi.tck.tests.implementation.simple.resource.env.EnvInjectionTest
```

**Comment by scottmarlow** [comment]
Fixed by updating `cdi.tck.version` to `cdi.tck-3-0.version` in:
`mvn  $JDK17OPTIONS clean verify -f jboss-tck-runner/pom.xml -Dincontainer -Dcdi.tck-3-0.version=${TCK_VERSION} -Dmaven.test.failure.ignore=true test -Dtest=org.jboss.cdi.tck.tests.implementation.simple.resource.env.EnvInjectionTest`
